#!/bin/sh

sudo apt install -y $(cat ~/pkglist.txt | awk '{print $1}') 

while read p; do
  sudo snap install $p --classic;
done <~/snaplist.txt


# Install oh my zsh 
sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh) --unattended"
rm ~/.zshrc
mv ~/.zshrc.pre-oh-my-zsh ~/.zshrc
chsh -s $(which zsh)

git config --global core.editor "code --wait"

fc-cache -f -v
